language: python

python:
  - 3.4
  - 3.5
  - 3.6

env:
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

matrix:
  exclude:
    - python: 3.4
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py34
    - python: 3.6
      env: TOXENV=py35

install:
  - pip install -r requirements.txt
  - pip install tox
  - pip install coveralls

script:
 - tox
